version: '3.6'
services: 
    prod:
        restart: always
        build: 
            context: .
            dockerfile: Dockerfile.nginx
        volumes: 
            - "./dist/TP01:/usr/share/nginx/html"
        ports: 
            - "80:80"


