version: '3.6'
services: 
    prod:
        restart: always
        build: 
            context: .
            dockerfile: Dockerfile.node
        volumes: 
            - "./dist/TP01:/home/node/app"
        ports: 
            - "80:80"
